# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'HBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HBuilder
     pod 'CocoaAsyncSocket', '~> 7.6.2'
     pod 'Masonry', '~> 1.1.0'
     pod 'DZNEmptyDataSet', '~> 1.8.1'
     pod 'JGProgressHUD', '~> 2.0.3'
     #< UIView frame 便捷访问扩展
     pod 'FrameAccessor', '~> 2.0'

end
